travis:
  secure:
    BINSTAR_TOKEN: RBtnFUDRtmPEgvYqeBeIXp4v/nwXkKm35oaf5wexIpQy61aQR2daW4iVKH6q+HrZjiGQtWbx7KU3ZePzHvW7sPoG2VWFYotwdCosmdD07NQSFUSdspNsf6+o/ifNQ8Int0o/MEQAJHZv+/BgF6obNtahLPH7a0cCB3+RxMG8pQLzYjSQgOuo+CBkKWKdkXZJskFhaqRVDwSX9IWoYqf7tkjAKc52Wxgc7N4eUFhzurDdEOl9iCp8CTIaxykYDRGPtQ92ljkF1DkpL4jupe4OAlK8EbKe1Fc8nVTy8T5GxKQDQg0PzRqxdFTn3dnFmQjFTTOf+LUdjo11QKQPcgtLoTJR6+TopCsGjr/YMXnWCtVQfHk++UnBHhDs+oI1X1ow5F3I/P29Xc3v9DBnt5w+ucFmLC2uxjIOF/Inu0/EjTsGb9paqrKJRqCh49ofUaKLZlckjNzpfq0/oR3OTeYyrcI7t8pcxM3fqGcw7Y87q2HKs1t9ndMnyWSYHaDOe1YO4usCI3KZ97kz+bYySCwIMwzdyY8Ymo4oQyKEGZGa0ZyUsKLHf2CSlV6QDc2vxuKR8kIydX2gEG3/hNgHTwucxDIlSnvEi5gZevWUgpMVuuNghIJTVi8i0n4Fjxb9kaA8JsmXVccT5iNDKCedLw0Zu53Oc25LYNxFvd9OXMk8Pp8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
